### ISSUE TITLE
Autoform conflict when using autoform add-ons

### ISSUE THREAD

**Issue by liuwenchao** [TelescopeJS/Telescope#1056] opened 2015-07-05 00:56 UTC
```
Uncaught Error: There are multiple templates named 'afCheckbox'. Each template needs a unique name.
Uncaught TypeError: Cannot read property 'AutoForm' of undefined
```

This is happening when using autoform add-on: autoform-file.

Looks like this is caused by having these 2 packages in the same time:
* 'sacha:autoform' required by telescope:lib
* 'aldeed:autoform' required by yogiben:autoform-file

**Comment by SachaG** [comment] 2015-07-05 01:44
Yes, this is normal. It'll go away once Autoform gets updated and we can switch back to the main Autoform package.

**Comment by liuwenchao** [comment] 2015-07-05 02:00
Do you have a timeline about this?

**Comment by SachaG** [comment] 2015-07-05 02:02
It depends on when @aldeed updates Autoform, it's not up to me.

**Comment by liuwenchao** [comment] 2015-07-05 02:25
I must have missed part of the story, what updates are we waiting for?

**Comment by SachaG** [comment] 2015-07-05 02:26
I submitted a PR for a feature needed by Telescope a couple weeks ago, but although it's been merged the new version hasn't been released yet, as far as I know. So in the meantime I'm using my own fork of the package.

**Comment by liuwenchao** [comment] 2015-07-05 02:32
Looks like this one https://github.com/aldeed/meteor-autoform/pull/865, Thanks!

BTW, I'm actually looking for file uploading ability in Telescope, i see it's pending in Trello, what's your thought on this, or do you have recommendations of other implementations that I can follow?

**Comment by SachaG** [comment] 2015-07-05 02:37
I'd recommend using something like https://atmospherejs.com/cosio55/autoform-cloudinary

Should work easily enough once we resolve the Autoform thing :)

**Comment by liuwenchao** [comment] 2015-07-05 02:43
Very valuable, Thank you very much!  It looks easier than autoform-file.

**Comment by liuwenchao** [comment] 2015-07-06 09:00
Hooray! https://github.com/aldeed/meteor-autoform/releases/tag/v5.3.1 @SachaG

**Comment by SachaG** [comment] 2015-07-06 09:39
No mention of my PR though, I don't think it's been merge back to master yet.

**Comment by liuwenchao** [comment] 2015-07-06 09:41
It is included in v5.3.1 (3eddcf7)

https://github.com/aldeed/meteor-autoform/commits/3eddcf7a36783d54639a76e804fc7fb4e1427ba4

**Comment by SachaG** [comment] 2015-07-06 09:44
That's the devel branch though, I think?

**Comment by liuwenchao** [comment] 2015-07-06 12:07
Right, but does that block updating aldeed:autoform to v5.3.1?

**Comment by SachaG** [comment] 2015-07-06 12:47
Well yeah because the changes I'm using are not merged in yet.

**Comment by liuwenchao** [comment] 2015-07-06 12:59
I don't really understand, aldeed is using devel as the default branch, releases are made from devel branch, and v5.3.1 does include your PRs ( I even pulled down aldeed:autoform@5.3.1 to verify ).

**Comment by SachaG** [comment] 2015-07-06 13:54
Oh sorry, I just assumed he was publishing the master branch, I guess you're right! I'll switch back to the regular Autoform for the next release of Telescope then :)

**Closed by SachaG** 2015-07-06 13:54 UTC

**Comment by aldeed** [comment] 2015-07-06 21:40
Still need to resolve some issues with devel branch before doing a bigger release, but hopefully soon. :)

**Comment by liuwenchao** [comment] 2015-07-06 23:09
Thank you both :wine_glass:

**Comment by SachaG** [comment] 2015-07-19 07:28
Just to clarify, I just tested it and I can confirm that the latest version of Autoform does *not* include my PR. So I can't switch to it just yet.

**Comment by liuwenchao** [comment] 2015-08-08 09:57
How about https://github.com/aldeed/meteor-autoform/releases/tag/v5.4.0 ? @SachaG

**Comment by SachaG** [comment] 2015-08-08 11:53
Yes, devel is switched back to regular autoform :)
