### ISSUE TITLE
npm-container

### ISSUE THREAD

**Issue by applocalizations** [TelescopeJS/Telescope#818] opened 2015-03-16 18:57 UTC
I just updated our project to the official upstream repo. A few seconds later I attempted to add a package that threw the following error: 

This project is at the latest release which is compatible with your current
package constraints.
=> Errors while upgrading packages:           
                                              
While selecting package versions:
error: unknown package: npm-container

What is wrong here? The package npm-container is apart of the official upstream repo's packages: https://github.com/TelescopeJS/Telescope/tree/master/packages/npm-container Why would Meteor return an error?

**Comment by SachaG** [comment] 2015-03-16 22:54
Which package were you trying to add?

**Comment by applocalizations** [comment] 2015-03-17 17:58
I was trying to add the `telescope-share-module` to enable social sharing. Is the `telescope-share-module` still capable of being added?

**Comment by SachaG** [comment] 2015-03-17 21:51
It's already added by default, so you shouldn't need to manually add it.

**Comment by applocalizations** [comment] 2015-03-17 21:52
How do we have the social sharing buttons appear then?

2015-03-17 14:51 GMT-07:00 Sacha Greif <notifications@github.com>:

> It's already added by default, so you shouldn't need to manually add it.
>

**Comment by SachaG** [comment] 2015-03-17 21:56
Oh, they're just hidden by default with CSS on the desktop view. You can enable them with `display:block`.

**Comment by applocalizations** [comment] 2015-03-17 21:57
There we go! Thanks!

2015-03-17 14:56 GMT-07:00 Sacha Greif <notifications@github.com>:

**Comment by applocalizations** [comment] 2015-03-17 21:59
Do you mean the CSS in the `telescope-share-module` or in a different file?

2015-03-17 14:57 GMT-07:00 Eric Giannini <eric.giannini@fulbrightmail.org>:

**Comment by applocalizations** [comment] 2015-03-17 22:04
Do you mean the CSS in the `telescope-share-module` or in a different file?

**Comment by SachaG** [comment] 2015-03-17 22:22
Closing this as duplicate of #817

**Closed by SachaG** 2015-03-17 22:22 UTC
