### ISSUE TITLE
Why the  reset  password email come from Meteor Accounts?

### ISSUE THREAD

**Issue by tvvocold** [TelescopeJS/Telescope#745] opened 2015-02-03 02:26 UTC
Why the Meteor Accounts (no-reply@meteor.com) send the reset passwd email even i set the email/mailURL value to my own(Mailgun).

FYI: here is the setting: 
```
smtp://postmaster@www.domain.org:mypasswd@smtp.mailgun.org:587/
```
and i had restart the App.

**Comment by SachaG** [comment] 2015-02-03 02:29
Duplicate of #480

**Closed by SachaG** 2015-02-03 02:29 UTC
