### ISSUE TITLE
How to create an String array on schema that works well with graphql

### ISSUE THREAD

**Issue by iamrommel** [TelescopeJS/Telescope#1610] opened 2017-04-07 06:03 UTC
I always got this error from server side console
```

MongoError: Positional projection 'tags.$' does not match the query document.
W20170407-13:55:17.459(8)? (STDERR)     at Object.Future.wait (C:\Users\iamrommel\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:449:15)
W20170407-13:55:17.459(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend._nextObject (packages/mongo/mongo_driver.js:1028:47)
W20170407-13:55:17.460(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend.forEach (packages/mongo/mongo_driver.js:1062:22)
W20170407-13:55:17.460(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend.map (packages/mongo/mongo_driver.js:1072:10)
W20170407-13:55:17.461(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend.fetch (packages/mongo/mongo_driver.js:1096:17)
W20170407-13:55:17.462(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.each.Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:911:44)
W20170407-13:55:17.462(8)? (STDERR)     at resolvers.list.resolver (packages/nq-workorder/lib/modules/resolvers.js:12:57)
W20170407-13:55:17.463(8)? (STDERR)     at resolveOrError (C:\Apps\gitlab.com\nq\node_modules\graphql\execution\execute.js:475:12)
W20170407-13:55:17.464(8)? (STDERR)     at resolveField (C:\Apps\gitlab.com\nq\node_modules\graphql\execution\execute.js:461:16)
W20170407-13:55:17.464(8)? (STDERR)     at C:\Apps\gitlab.com\nq\node_modules\graphql\execution\execute.js:275:18
W20170407-13:55:17.464(8)? (STDERR)     - - - - -
W20170407-13:55:17.465(8)? (STDERR)     at Function.MongoError.create (C:\Users\iamrommel\AppData\Local\.meteor\packages\npm-mongo\2.2.24\npm\node_modules\mongodb-core\lib\error.js:31:11)
W20170407-13:55:17.465(8)? (STDERR)     at queryCallback (C:\Users\iamrommel\AppData\Local\.meteor\packages\npm-mongo\2.2.24\npm\node_modules\mongodb-core\lib\cursor.js:212:36)
W20170407-13:55:17.465(8)? (STDERR)     at C:\Users\iamrommel\AppData\Local\.meteor\packages\npm-mongo\2.2.24\npm\node_modules\mongodb-core\lib\connection\pool.js:455:18
W20170407-13:55:17.466(8)? (STDERR)     at nextTickCallbackWith0Args (node.js:436:9)
W20170407-13:55:17.466(8)? (STDERR)     at process._tickCallback (node.js:365:13)
W20170407-13:55:37.355(8)? (STDERR) MongoError: Positional projection 'tags.$' does not match the query document.
W20170407-13:55:37.356(8)? (STDERR)     at Object.Future.wait (C:\Users\iamrommel\AppData\Local\.meteor\packages\meteor-tool\1.4.3_2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\future.js:449:15)
W20170407-13:55:37.357(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend._nextObject (packages/mongo/mongo_driver.js:1028:47)
W20170407-13:55:37.357(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend.forEach (packages/mongo/mongo_driver.js:1062:22)
W20170407-13:55:37.357(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend.map (packages/mongo/mongo_driver.js:1072:10)
W20170407-13:55:37.358(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.extend.fetch (packages/mongo/mongo_driver.js:1096:17)
W20170407-13:55:37.358(8)? (STDERR)     at [object Object].meteorInstall.node_modules.meteor.mongo.mongo_driver.js._.each.Cursor.(anonymous function) [as fetch] (packages/mongo/mongo_driver.js:911:44)
W20170407-13:55:37.359(8)? (STDERR)     at resolvers.list.resolver (packages/nq-workorder/lib/modules/resolvers.js:12:57)
W20170407-13:55:37.359(8)? (STDERR)     at resolveOrError (C:\Apps\gitlab.com\nq\node_modules\graphql\execution\execute.js:475:12)
W20170407-13:55:37.359(8)? (STDERR)     at resolveField (C:\Apps\gitlab.com\nq\node_modules\graphql\execution\execute.js:461:16)
W20170407-13:55:37.360(8)? (STDERR)     at C:\Apps\gitlab.com\nq\node_modules\graphql\execution\execute.js:275:18
W20170407-13:55:37.360(8)? (STDERR)     - - - - -
W20170407-13:55:37.360(8)? (STDERR)     at Function.MongoError.create (C:\Users\iamrommel\AppData\Local\.meteor\packages\npm-mongo\2.2.24\npm\node_modules\mongodb-core\lib\error.js:31:11)
W20170407-13:55:37.361(8)? (STDERR)     at queryCallback (C:\Users\iamrommel\AppData\Local\.meteor\packages\npm-mongo\2.2.24\npm\node_modules\mongodb-core\lib\cursor.js:212:36)
W20170407-13:55:37.361(8)? (STDERR)     at C:\Users\iamrommel\AppData\Local\.meteor\packages\npm-mongo\2.2.24\npm\node_modules\mongodb-core\lib\connection\pool.js:455:18
W20170407-13:55:37.368(8)? (STDERR)     at nextTickCallbackWith0Args (node.js:436:9)
W20170407-13:55:37.369(8)? (STDERR)     at process._tickCallback (node.js:365:13)

```

and my schema was written like this
![image](https://cloud.githubusercontent.com/assets/177265/24787376/8c293d96-1b9a-11e7-8e42-e9f03c265419.png)

I was able to save the document correctly using "newMutation" with "tags" field as arrays of strings in my mongodb. I was able to retrieved it correctly too if there are results, but if my **results are empty**(let say i have the selector "_id=XXX" (that document does not exists from mongodb), i got this error. Im not sure which and where to start debugging this.

**Comment by SachaG** [comment] 2017-04-07 07:11
That schema looks correct to me. I'm not sure why you're getting this specific error, but it looks like the problem is coming from the list resolver (`resolvers.list.resolver`). I would start by adding some console.logs in there to see what selector and options are being used to query the db.

**Comment by SachaG** [comment] 2017-04-07 07:17
If you can't figure it out, feel free to share a link to your repo here or on slack.telescopeapp.org and I'll try to take a look.

**Comment by iamrommel** [comment] 2017-04-07 08:52
by the way, removing the 
```

 viewableBy: ['guests'],
    insertableBy: ['members'],
    editableBy: ['members'],
```
from tag.$ makes it work.

the resolver is the just a copy-paste-edit from movies example
![image](https://cloud.githubusercontent.com/assets/177265/24792929/917bee34-1bb2-11e7-88a1-49fc78b7f345.png)

**Comment by SachaG** [comment] 2017-04-07 09:22
Glad you figured it out! I'll close this for now.

**Closed by SachaG** 2017-04-07 09:22 UTC
