### ISSUE TITLE
Adding custom fields to sign up/sign in forms.

### ISSUE THREAD

**Issue by PranayShah** [TelescopeJS/Telescope#831] opened 2015-03-19 13:28 UTC
I tried this but my calls to AccountsTemplates.addFileds and removeFiled from a custom were overwritten by the call to the same methods in the main Telescope code. How do I solve this?

**Comment by splendido** [comment] 2015-03-19 13:52
Hello there!

Where are you trying to change the fields? In which file?
Consider that each file is loaded with a particular and well defined order: see `File Load Order` inside the [Structuring your App](http://docs.meteor.com/#/full/structuringyourapp) section of Meteor docs.

**Comment by PranayShah** [comment] 2015-03-19 14:02
But the package code is always loaded before the main code, right? And my
code is in a package.

Hello there!

Where are you trying to change the fields? In which file?
Consider that each file is loaded with a particular and well defined order:
see File Load Order inside the Structuring your App
<http://docs.meteor.com/#/full/structuringyourapp> section of Meteor docs.

—
Reply to this email directly or view it on GitHub
<https://github.com/TelescopeJS/Telescope/issues/831#issuecomment-83589346>.

**Comment by splendido** [comment] 2015-03-19 14:18
Ok, now I see...
You could try to wrap your call to `AccountsTemplates` inside a 

```javascript
Meteor.startup(function(){
  // AT confgi here
  // ...
});
```

but there would probably be another *race condition*...
...lets try!

**Comment by PranayShah** [comment] 2015-03-19 14:27
I think I am saying something incorrectly here. But my idea is that my
package's call to AccountsTemplates should happen after the main code's.
Wouldn't putting it in Meteor.startup do the opposite of it?

**Comment by splendido** [comment] 2015-03-19 14:34
well, all stuff inside a `meteor.startup` is actually run after all regular file loading is finished...

the big question is: will your `Meteor.startup` run after or before [the one](https://github.com/meteor-useraccounts/core/blob/master/lib/server.js#L168-171) used by `accountstemplates` to initialize itself?? :-)

**Comment by PranayShah** [comment] 2015-03-19 14:36
Oh thanks for clearing that up. I will check and let you know as soon as I
can.

**Comment by splendido** [comment] 2015-04-01 22:19
any news on this @PranayShah?

**Comment by PranayShah** [comment] 2015-04-04 19:53
This is what the AccountsTemplates object looks like when logged from within a ```Meteor.startup (function()) ``` within a package. And the error which I was getting. There are no methods associated with the AccountsTemplates object.

```
I20150405-01:14:19.546(5.5)? { options: 
I20150405-01:14:19.546(5.5)?    { enablePasswordChange: false,
I20150405-01:14:19.547(5.5)?      showForgotPasswordLink: true,
I20150405-01:14:19.547(5.5)?      confirmPassword: false,
I20150405-01:14:19.548(5.5)?      overrideLoginErrors: true,
I20150405-01:14:19.548(5.5)?      lowercaseUsername: true,
I20150405-01:14:19.548(5.5)?      negativeFeedback: false,
I20150405-01:14:19.548(5.5)?      positiveFeedback: false,
I20150405-01:14:19.548(5.5)?      negativeValidation: true,
I20150405-01:14:19.548(5.5)?      positiveValidation: true,
I20150405-01:14:19.549(5.5)?      privacyUrl: 'privacy',
I20150405-01:14:19.549(5.5)?      termsUrl: 'tos',
I20150405-01:14:19.549(5.5)?      showReCaptcha: false,
I20150405-01:14:19.549(5.5)?      showAddRemoveServices: false,
I20150405-01:14:19.550(5.5)?      showLabels: true,
I20150405-01:14:19.550(5.5)?      showPlaceholders: true,
I20150405-01:14:19.550(5.5)?      defaultState: 'signIn',
I20150405-01:14:19.550(5.5)?      forbidClientAccountCreation: false,
I20150405-01:14:19.550(5.5)?      sendVerificationEmail: false,
I20150405-01:14:19.550(5.5)?      socialLoginStyle: 'popup',
I20150405-01:14:19.551(5.5)?      homeRoutePath: '/',
I20150405-01:14:19.551(5.5)?      redirectTimeout: 2000,
I20150405-01:14:19.551(5.5)?      onSubmitHook: undefined,
I20150405-01:14:19.552(5.5)?   _initialized: true }
I20150405-01:14:19.608(5.5)? Exception while invoking method 'userOrOrg' TypeError: Object [object Object] has no method 'removeFields'
I20150405-01:14:19.608(5.5)?     at [object Object].Meteor.methods.userOrOrg (packages/batmobile-users/lib/atConfig.js:54:1)
I20150405-01:14:19.608(5.5)?     at [object Object].methodMap.(anonymous 
```

**Comment by SachaG** [comment] 2015-04-05 08:26
Just wanted to say I'm planning on looking into this next week.

**Comment by splendido** [comment] 2015-04-06 08:52
@PranayShah, I think I've just spotted the error: it's `removeFiled` and not `removeFields`!
...btw, you should see all methods from the class' prototype.

Lets also have a look at the [Remove Fields](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#remove-fields) section.

**Comment by PranayShah** [comment] 2015-04-06 18:36
This does not work even with AccountsTemplates.removeField . The error shown now is:
``` Exception while invoking method 'userOrOrg' Error: AccountsTemplates.removeField should strictly be called before AccountsTemplates.init!``` . And this is even after calling the method from a Meteor.startup block.

**Comment by splendido** [comment] 2015-04-06 20:20
Yeah, I suspected this... :(

Your `Meteor.startup` is executed after the one used by `useraccounts` to trigger its initialization.

So, in summary:
* if you work on regular top level code, being inside a package, your file is loaded before Telescope's top level code and your changes are somehow overwritten by Telescope's configuration file
* if you run some configuration inside `Meteor.startup`, this is executed after the `Meteor.startup` used by `useraccounts` because, as another package, it's probably loaded first...

The only way would be getting your package loading before `useraccounts` so that your `Meteor.startup` goes before the UA initialization.
But unfortunately, we have no means to say a package should come before another one...
We can do the opposite, specifying that a package depends on another, but this is not the case :(

**Comment by PranayShah** [comment] 2015-04-07 04:52
So can we hope to work this out. This seems like a pretty necessary
requirement to me.

**Comment by PranayShah** [comment] 2015-04-25 07:11
@splendido Any updates on this?

**Comment by splendido** [comment] 2015-04-25 07:42
no, not really

what if you remove all AT stuff from Telescope and configure everything inside your package?

**Comment by PranayShah** [comment] 2015-04-25 07:47
Do you mean removing Telescope's dependency on AT entirely, hence modifying
the core Telescope code for this and then adding  it back again but as a
dependency of my own package? So I feel this is bound to work but does it
not sound like an overkill to do something simple like adding extra fields
to the user's schema right at login, specially since AT supports all that
so beautifully.

**Comment by splendido** [comment] 2015-04-25 07:56
could you explain how you'd like to change the fields?
I've just read again all this thread but I can't get it.

**Comment by PranayShah** [comment] 2015-04-25 12:05
All I want to do is add fields with calls to AT.addField,  like it is
documented in the Accounts templates package.  These calls have no effect.

**Comment by splendido** [comment] 2015-04-25 13:40
Ok, but I'd say that new fields should be kept...
Are you by chance trying to change `email` or `password` which are the ones [changed by Telescope](https://github.com/TelescopeJS/Telescope/blob/master/lib/config/at_config.js#L27-43)?

**Comment by PranayShah** [comment] 2015-04-25 14:36
Indeed I was trying to change the `email` and `password` fields. And I understand that is not possible. But, that aside, how would you suggest I specify a different template to be used when the `/register` and `/sign-in` links are navigated to? Specifying `AccountsTemplates.configureRoutes ( ) ` with the template option specifying a template does not work. I realize I may be confusing you here by talking about different issues in the same thread but I am essentially trying to solve the same problem here. In my use case, there are 2 kinds of users, normal users and organizations. I want to be able to provide different sign-up fields for either of them depending on say, a Session variable, which is set according to the type of user selected while in the `/register` route itself. Sorry for a long and almost useless reply.

**Comment by splendido** [comment] 2015-04-25 14:49
Hey @PranayShah it is not possible to implement this last request in case you'd like to have the `organization` field required: see [this issue](https://github.com/meteor-useraccounts/core/issues/358)

Btw, to get different templates you should override the default one (e.g. with `aldeed:template-extension`) so you can switch something on the fly...

This said, I'm sorry but in your case the only solution I see is to delete the [at_config.js](https://github.com/TelescopeJS/Telescope/blob/master/lib/config/at_config.js) file from Telescope and keep only your one...

Perhaps we should reason about this with @SachaG?
The only other solution I can see would be not to change default useraccounts settings so that Telescope users/developers could change them on their own?

I'd say that we should wait for `useraccounts@2.0` (which is currently in the works...) so to agree on some default settings (options + routes...).

Thoughts?

**Comment by PranayShah** [comment] 2015-04-25 15:08
Hey thanks for taking the time to read through all of it.  I am not sure
what you mean by agreeing  on default settings.  In my opinion the defaults
provided by the useraccounts package are perfect and changing them would
not affect this issue of mine anyway.  A core difference I see in using the
package here versus in any other project is that I lose all the flexibility
that useraccounts provides like being able to change the route's path,
templates which is rendered for that path etc. And yes,  your suggestion on
letting Telescope users/developers configure these settings for themselves
makes compete sense to me.
Besides until now what was I trying  to do was have a custom template which
had a call to `atForm` within it.  I was not trying to change templates on
the fly. Instead I was calling AT.addField and At.removeFields on the fly,
if you will. But it did not work right from specifying a different template
to the part where I was adding and removing fields, an issue which you have
already referenced to.
Sorry again :P

**Comment by splendido** [comment] 2015-04-25 15:16
No worries, you're welcome!

The thing about adding/removing fields at *run time* on the client is impossible: this is one of the selling points of useraccounts and all the structure was designed to enforce them!
If you set a required field, the server won't let you register if you don't provide it: so javascript magicians cannot tweak your required fields from the client side ;-)

When I say
> to agree on some default settings
is to have Telescope simply pulling in required `useraccounts` packages and have no `at_config.js` file so to let developers do whatever they wish...

Hope it's clearer now.

**Comment by PranayShah** [comment] 2015-04-25 15:38
But I was calling at.Removefield server side via a Meteor method.
Anyway thanks a lot for all the help.  So appreciated.

**Comment by splendido** [comment] 2015-04-25 15:54
wow... super hacky @PranayShah!
I wouldn't to that: what if a *regular* user tries to register in the meanwhile?
You'd face critical races ;-)

**Comment by PranayShah** [comment] 2015-04-25 18:08
Totally agreed :)

**Comment by xavcz** [comment] 2016-10-01 11:45
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍

**Closed by xavcz** 2016-10-01 11:45 UTC
Labels: user accounts
