### ISSUE TITLE
Post authorName is name of submitter, not author 

### ISSUE THREAD

**Issue by brettpthomas** [TelescopeJS/Telescope#344] opened 2014-07-27 13:10 UTC
If an admin submits a story with user A (non admin) as the author: authorName is the name of the admin, but profileUrl is the URL for user A.

**Comment by massimilianomarini** [comment] 2015-02-10 14:16
I've tested this bug with Chrome 40 and the latest - master branch - Telescope release: I can't reproduce this bug, the author name is shown correctly.

**Comment by xavcz** [comment] 2016-09-28 11:52
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)).

The Legacy version is no longer supported. I'm closing this issue. I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome! 

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) and ask any question, you are welcome! 👍

**Closed by xavcz** 2016-09-28 11:52 UTC
Labels: bug
