### ISSUE TITLE
"load more" button doesn't work in FireFox

### ISSUE THREAD

**Issue by BanzaiTokyo** [TelescopeJS/Telescope#1007] opened 2015-06-08 07:35 UTC
It console.logs: 
ReferenceError: event is not defined

**Comment by tobika** [comment] 2015-06-08 08:40
thanks for the info, have the same problem but thought it was installation error
now at least I can use chrome until the fix if needed

**Comment by brianshumate** [comment] 2015-06-09 01:40
This is a duplicate of #928.

**Closed** 2015-08-01 07:18 UTC
