### ISSUE TITLE
Glyphicons don't want to dispaly properly

### ISSUE THREAD

**Issue by wende** [TelescopeJS/Telescope#1042] opened 2015-06-24 13:34 UTC
When doing quickForm with an Array form displays weird and glyphicons don't show at all
![screenshot from 2015-06-24 02 06 17](https://cloud.githubusercontent.com/assets/4634386/8331085/8b3b37c0-1a86-11e5-9b17-649a09027476.png)

**Comment by jshimko** [comment] 2015-06-26 13:28
It would be helpful to see whatever code you're using.  It's pretty difficult to diagnose a customization issue from a screenshot.  And since this is an issue with code you've added and not Telescope core, a sample repo reproducing the issue would be very helpful.

**Comment by iraasta** [comment] 2015-06-26 14:56
This is the the core. No code added except for changed Collection scheme from `String` to 
`[String]`

**Comment by jshimko** [comment] 2015-06-26 15:27
Ok, I just changed a post schema item from `String` to `[String]` and I don't get the same result.  So I think there's more to it than that.  How about the icons?  Those don't really have anything to do with the schema.

**Comment by iraasta** [comment] 2015-06-26 15:45
That's weird. I didn't change anything except for that.
Well, icons are added automatically by quickForm i guess, but they're not displaying.
I'll try to reproduce this effect on a clear copy and host it on heroku. I'll see if it's just something about my "copy" ;)
Thanks for Your effort. I will elaborate in a moment

**Comment by iraasta** [comment] 2015-06-26 19:20
I reproduced te same thing:
1. Cloned this repo
2. Changed `String` to `[String]`
3. Deployed
4. Profit

http://quickformtest.herokuapp.com/submit
Check by Yourselves.
Login: test
Password: test

**Comment by jshimko** [comment] 2015-06-26 19:35
It's because Autoform is using Glyph icons for the plus/minus buttons that add/remove new text fields. Telescope isn't using that functionality anywhere, so the full Glyph package isn't included and the buttons aren't styled in the form template.  

Adding `chriswessels:glyphicons-halflings` makes the icons show up, but the button layout styles are still a little broken (again, because these icons and buttons are not used anywhere in Telescope).  

My suggestion for a quick fix is to add one of the Glyph icons packages on Atmosphere and then style your custom input with CSS in your custom package.  If you'd like to contribute the styling back to Telescope so other people can add array fields, we'd be happy to accept a pull request.

Thanks for pointing this out.

**Comment by xavcz** [comment] 2016-10-01 11:53
Hey, @wende! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue.

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍

**Closed by xavcz** 2016-10-01 11:53 UTC
Labels: enhancement
