### ISSUE TITLE
Subscriptions on subsequent pages with different field filters (avatarOptions, privacyOptions)

### ISSUE THREAD

**Issue by yourcelf** [TelescopeJS/Telescope#858] opened 2015-03-27 15:15 UTC
It looks like subscribed user models are not getting updated when navigating to a page with a subscription to the same model but different fields filter.

 1. Go to a post list page, which loads the ``postListUsers`` subscription, which is filtered by ``avatarOptions``.
 2. Click through to a user's profile page.  This page would subscribe to ``singleUser`` with fields filtered by the more inclusive ``privacyOptions``, but since the model had already been subscribed via ``postListUsers``, it isn't re-fetched.  It will be missing fields not present in ``avatarOptions``.

A hard refresh will pull down the missing fields by re-running the subscription to ``singleUser`` from scratch.

Not sure if it is this issue https://github.com/meteor/meteor/issues/3259; that was closed basically because no one created a reproduction.  https://github.com/meteor/meteor/issues/3259#issuecomment-69462588 suggests that this issue affetcs non-top-level fields only (e.g. "profile.foo").  A workaround could be to just use the full ``privacyOptions`` query each time rather than ``avatarOptions``, at the expense of a bit more data transfer.

**Comment by juliomac** [comment] 2015-08-22 17:40
I have been able to make a repo to reproduce the issue. It also happens on top level fields.


Please see : https://github.com/juliomac/Bug-MultiSubs-DifSetofFields-3259

**Comment by SachaG** [comment] 2015-08-23 01:23
Yeah you're right. I recently ran into issues around this. It's really hard to fix because this problem is in Meteor itself… It shouldn't happen on top-level fields though, only `telescope.foo` ones.

**Comment by SachaG** [comment] 2015-08-23 01:27
The previous related issue I ran into was that I was subscribing to the current user once for their profile, and then again when listing their posts. I ended up disabling the second subscription because it was overriding the first one: https://github.com/TelescopeJS/Telescope/commit/2c1d3b3fb9f1e32df540e85eabd72cdafcc2953e

**Comment by SachaG** [comment] 2015-08-23 01:28
Also this post has a detailed explanation of the problem, and a couple solutions: https://medium.com/@MaxDubrovin/workaround-for-meteor-limitations-if-you-want-to-sub-for-more-nested-fields-of-already-received-docs-eb3fdbfe4e07

**Comment by juliomac** [comment] 2015-08-23 02:26
I did bump into this problem when I was trying to subscribe to new nested fields. I guess, that is the nature for the use of nested fields, to keep details and other information we may or may not want to publish.

However, when I was trying to reproduce the issue, in my attempt to make it as simpler as possible, it turns out it was also reproduceable on top level fields.

If I understood right @MaxDubrovin explanation, I believe the reason that his workaround worked was not due to top-levelling the fields in itself. It was because, in order to top-level it, he had to create a separate collection.

I think the issue happens when we attempt to subscribe to new fields of the same document at the same collection, not matter if top or nested.

On my real application, that was what I did to fix it as well. Just flattened my doc structure by creating a new collection and relate them by ids.

PS: I have now properly uploaded the Reproduction Repo.

**Comment by SachaG** [comment] 2015-08-24 00:54
So I think I'm going to just publish all the data all the time, to avoid conflicts. It's not very efficient but I don't want to add extra complexity to the app just to implement a workaround a bug that might be fixed at the framework level in the future.

**Comment by juliomac** [comment] 2015-08-24 14:29
It turned out it was some silly bug on my example code. The updated example code could not reproduce the issue after all.

**Comment by SachaG** [comment] 2015-08-24 23:26
Well I did reproduce it :)

**Comment by xavcz** [comment] 2016-10-01 11:42
Hey, folks! Telescope has changed a lot in the past months, and there is a new React-based version, [Telescope Nova](https://github.com/TelescopeJS/Telescope) ([intro video](https://www.youtube.com/watch?v=_cLv6fH-PSQ&index=1&list=PLBoa_Q6hVeSzChsSi8X8x3FQ8NN2D73fB)). If you know Crater, it runs on the latest version.

The Legacy version is no longer supported. I'm closing this issue. And we are slowly leaving pub/sub for Apollo 💯 

I invite you to check [the new version](https://github.com/TelescopeJS/Telescope), it's awesome!

Happy hacking! 🚀

Ps: by the way, don't hesitate to join the [Slack](http://slack.telescopeapp.org) to ask any question, you are welcome! 👍

**Closed by xavcz** 2016-10-01 11:42 UTC
Labels: bug
