### ISSUE TITLE
Invite link in the email not working

### ISSUE THREAD

**Issue by ntnlbd** [TelescopeJS/Telescope#1234] opened 2016-01-21 00:36 UTC
I've deployed the app to meteor.com and when I send an invite as an admin the email arrives to the destination mailbox all good. But clicking on the link in the email opens new tab in browser and points to url http://atsignup/

Any idea what might be going wrong here?

**Comment by JacopKane** [comment] 2016-01-24 13:51
Same here

**Comment by SachaG** [comment] 2016-01-24 13:54
Closing as duplicate of https://github.com/TelescopeJS/Telescope/issues/1194

**Closed by SachaG** 2016-01-24 13:54 UTC
